[package]
name = "mcp_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
url = { version = "2.5", features = ["serde"] }
serde_json = "1.0.137"
anyhow = "1.0.95"
base64 = "0.22"
log = "0.4.25"
tracing = "0.1"
tracing-subscriber = "0.3"